# Generated by Django 5.2.17 on 2026-08-10 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_phone_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Bilgi'), ('warning', 'Uyarı'), ('critical', 'Kritik')], default='warning', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_analysis_control_name_per_owner')],
            },
        ),
        migrations.CreateModel(
            name='DocumentAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], max_length=16)),
                ('controls', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_analysis_runs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='api.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='api_documen_documen_523582_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('char_start', models.PositiveIntegerField()),
                ('char_end', models.PositiveIntegerField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.document')),
            ],
            options={
                'ordering': ['document_id', 'position'],
                'indexes': [models.Index(fields=['document', 'position'], name='api_documen_documen_b9c0f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'position'), name='unique_chunk_position_per_document')],
            },
        ),
    ]
