# Generated by Django 5.2.17 on 2026-08-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_document_owners(apps, schema_editor):
    """Infer owners only when every job for a document has the same owner."""

    AsyncJob = apps.get_model("api", "AsyncJob")
    Document = apps.get_model("api", "Document")
    database = schema_editor.connection.alias

    inferred = {}
    ambiguous = set()
    job_owners = (
        AsyncJob.objects.using(database)
        .exclude(document_id=None)
        .order_by()
        .values_list("document_id", "owner_id")
        .distinct()
    )
    for document_id, owner_id in job_owners.iterator():
        existing_owner = inferred.get(document_id)
        if existing_owner is not None and existing_owner != owner_id:
            ambiguous.add(document_id)
        else:
            inferred[document_id] = owner_id

    for document_id in ambiguous:
        inferred.pop(document_id, None)

    documents_by_owner = {}
    for document_id, owner_id in inferred.items():
        documents_by_owner.setdefault(owner_id, []).append(document_id)
    for owner_id, document_ids in documents_by_owner.items():
        Document.objects.using(database).filter(
            pk__in=document_ids,
            owner__isnull=True,
        ).update(owner_id=owner_id)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_flightpermit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_document_owners, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["owner", "-created_at"],
                name="api_doc_owner_created_idx",
            ),
        ),
    ]
