# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_flightpermit_recommendation_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormProcessRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("process_code", models.CharField(db_index=True, max_length=64)),
                ("template_code", models.CharField(db_index=True, max_length=64)),
                ("record_number", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("in_review", "İncelemede"),
                            ("approved", "Onaylandı"),
                            ("archived", "Arşivlendi"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_form_process_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_form_process_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "record_number"],
                "indexes": [
                    models.Index(
                        fields=["process_code", "status", "updated_at"],
                        name="api_formpro_process_b3f6c6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("process_code", "record_number"),
                        name="unique_form_record_number_per_process",
                    )
                ],
            },
        ),
    ]
