# Generated by Django 5.2.17 on 2026-08-21 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_edk_roles(apps, schema_editor):
    user_model = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    group_model = apps.get_model("auth", "Group")
    applicant_group, _ = group_model.objects.get_or_create(name="EDK Başvuru Sahibi")
    approver_group, _ = group_model.objects.get_or_create(name="EDK Onaylayıcı")

    for user in user_model.objects.filter(is_active=True).iterator():
        user.groups.add(approver_group if user.is_staff else applicant_group)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_remove_flightpermit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EDKApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_title", models.CharField(max_length=240)),
                ("project_name", models.CharField(max_length=160)),
                ("requested_date", models.DateField()),
                ("location", models.CharField(max_length=200)),
                ("participants", models.TextField(max_length=2000)),
                ("purpose", models.TextField(max_length=3000)),
                ("agenda", models.TextField(max_length=5000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Onay Bekliyor"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decision_note", models.TextField(blank=True, max_length=2000)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("minutes_file_name", models.CharField(blank=True, max_length=255)),
                ("minutes_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edk_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_edk_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["applicant", "status", "created_at"],
                        name="api_edk_applicant_status_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="api_edk_status_created_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_edk_roles, migrations.RunPython.noop),
    ]
