# Generated by Django 5.2.17 on 2026-09-27 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_update_edk_application_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormNumberingConfigLock',
            fields=[
                ('template_code', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormNumberMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(max_length=64)),
                ('target_field', models.CharField(max_length=128)),
                ('format_code', models.SlugField()),
                ('enabled', models.BooleanField(default=True)),
                ('context_sources', models.JSONField(default=dict)),
                ('format_snapshot', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_code', 'target_field'],
                'constraints': [models.UniqueConstraint(fields=('template_code', 'target_field'), name='unique_form_number_target')],
            },
        ),
        migrations.CreateModel(
            name='FormNumberAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('original_record_id', models.PositiveBigIntegerField(null=True)),
                ('target_field', models.CharField(max_length=128)),
                ('mapping_snapshot', models.JSONField(default=dict)),
                ('form_snapshot', models.JSONField(default=dict)),
                ('provider_payload', models.JSONField(default=dict)),
                ('locked_values', models.JSONField(default=dict)),
                ('expected_updated_at', models.DateTimeField(null=True)),
                ('attachment', models.FileField(blank=True, max_length=500, upload_to='form_numbering/%Y/%m/')),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('provider_id', models.PositiveBigIntegerField(null=True)),
                ('document_number', models.TextField(blank=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='number_allocations', to='api.formprocessrecord')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.formnumbermapping')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('record', 'target_field'), name='unique_form_number_allocation_target')],
            },
        ),
    ]
