# Generated by Django 5.2.17 on 2026-09-27 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_edk_jira_tracking'),
        ('api', '0026_formnumberingconfiglock_formnumbermapping_and_more'),
    ]

    operations = [
    ]
