from django.urls import path

from .views import (
    AdminUserListView,
    AdminUserStatusView,
    CsrfTokenView,
    CurrentUserView,
    DocumentDetailView,
    DocumentListView,
    DocumentUploadView,
    LoginView,
    LogoutView,
    PanelResponsibleDetailView,
    PanelResponsibleListCreateView,
    ProjectDetailView,
    ProjectListCreateView,
    ProjectPanelDetailView,
    ProjectPanelListCreateView,
    RegisterView,
    TechnicalDocumentDetailView,
    TechnicalDocumentListCreateView,
    TechnicalDocumentNotifyView,
    health_check,
)

urlpatterns = [
    path("health/", health_check, name="health-check"),
    path("auth/csrf/", CsrfTokenView.as_view(), name="csrf-token"),
    path("auth/me/", CurrentUserView.as_view(), name="current-user"),
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/logout/", LogoutView.as_view(), name="logout"),
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("admin/users/", AdminUserListView.as_view(), name="admin-user-list"),
    path("admin/users/<int:user_id>/status/", AdminUserStatusView.as_view(), name="admin-user-status"),
    path("organization/projects/", ProjectListCreateView.as_view(), name="project-list"),
    path("organization/projects/<int:project_id>/", ProjectDetailView.as_view(), name="project-detail"),
    path(
        "organization/projects/<int:project_id>/panels/",
        ProjectPanelListCreateView.as_view(),
        name="project-panel-list",
    ),
    path(
        "organization/panels/<int:panel_id>/",
        ProjectPanelDetailView.as_view(),
        name="project-panel-detail",
    ),
    path(
        "organization/panels/<int:panel_id>/responsibles/",
        PanelResponsibleListCreateView.as_view(),
        name="panel-responsible-list",
    ),
    path(
        "organization/responsibles/<int:responsible_id>/",
        PanelResponsibleDetailView.as_view(),
        name="panel-responsible-detail",
    ),
    path("documents/", DocumentListView.as_view(), name="document-list"),
    path("documents/upload/", DocumentUploadView.as_view(), name="document-upload"),
    path("documents/<int:document_id>/", DocumentDetailView.as_view(), name="document-detail"),
    path(
        "technical-documents/",
        TechnicalDocumentListCreateView.as_view(),
        name="technical-document-list",
    ),
    path(
        "technical-documents/<int:technical_document_id>/",
        TechnicalDocumentDetailView.as_view(),
        name="technical-document-detail",
    ),
    path(
        "technical-documents/<int:technical_document_id>/notify/",
        TechnicalDocumentNotifyView.as_view(),
        name="technical-document-notify",
    ),
]
