from django.urls import path

from .views import (
    AdminUserListView,
    AdminUserStatusView,
    AnalysisControlDetailView,
    AnalysisControlListCreateView,
    AsyncJobCancelView,
    AsyncJobDetailView,
    AsyncJobListView,
    CsrfTokenView,
    CurrentUserView,
    DocumentDetailView,
    DocumentAnalysisRunListView,
    DocumentControlRunView,
    DocumentListView,
    DocumentUploadView,
    DocumentRagQueryView,
    FlightPermitDetailView,
    FlightPermitDocumentView,
    FlightPermitListCreateView,
    LoginView,
    LogoutView,
    OllamaChatView,
    OllamaPullView,
    OllamaStatusView,
    OllamaUnloadView,
    PanelResponsibleDetailView,
    PanelResponsibleListCreateView,
    GroupPersonListCreateView,
    PersonDetailView,
    PersonGroupDetailView,
    PersonGroupListCreateView,
    ProjectDetailView,
    ProjectListCreateView,
    ProjectPanelDetailView,
    ProjectPanelListCreateView,
    RegisterView,
    TechnicalDocumentDetailView,
    TechnicalDocumentListCreateView,
    TechnicalDocumentNotifyView,
    WordTableParseView,
    WordToJiraPublishView,
    health_check,
)

urlpatterns = [
    path("health/", health_check, name="health-check"),
    path("auth/csrf/", CsrfTokenView.as_view(), name="csrf-token"),
    path("auth/me/", CurrentUserView.as_view(), name="current-user"),
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/logout/", LogoutView.as_view(), name="logout"),
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("admin/users/", AdminUserListView.as_view(), name="admin-user-list"),
    path("admin/users/<int:user_id>/status/", AdminUserStatusView.as_view(), name="admin-user-status"),
    path("organization/projects/", ProjectListCreateView.as_view(), name="project-list"),
    path("organization/projects/<int:project_id>/", ProjectDetailView.as_view(), name="project-detail"),
    path(
        "organization/projects/<int:project_id>/panels/",
        ProjectPanelListCreateView.as_view(),
        name="project-panel-list",
    ),
    path(
        "organization/panels/<int:panel_id>/",
        ProjectPanelDetailView.as_view(),
        name="project-panel-detail",
    ),
    path(
        "organization/panels/<int:panel_id>/responsibles/",
        PanelResponsibleListCreateView.as_view(),
        name="panel-responsible-list",
    ),
    path(
        "organization/responsibles/<int:responsible_id>/",
        PanelResponsibleDetailView.as_view(),
        name="panel-responsible-detail",
    ),
    path("organization/person-groups/", PersonGroupListCreateView.as_view(), name="person-group-list"),
    path(
        "organization/person-groups/<int:group_id>/",
        PersonGroupDetailView.as_view(),
        name="person-group-detail",
    ),
    path(
        "organization/person-groups/<int:group_id>/people/",
        GroupPersonListCreateView.as_view(),
        name="group-person-list",
    ),
    path(
        "organization/people/<int:person_id>/",
        PersonDetailView.as_view(),
        name="person-detail",
    ),
    path("documents/", DocumentListView.as_view(), name="document-list"),
    path("documents/upload/", DocumentUploadView.as_view(), name="document-upload"),
    path("documents/<int:document_id>/", DocumentDetailView.as_view(), name="document-detail"),
    path("flight-permits/", FlightPermitListCreateView.as_view(), name="flight-permit-list"),
    path(
        "flight-permits/<int:flight_permit_id>/",
        FlightPermitDetailView.as_view(),
        name="flight-permit-detail",
    ),
    path(
        "flight-permits/<int:flight_permit_id>/document/",
        FlightPermitDocumentView.as_view(),
        name="flight-permit-document",
    ),
    path(
        "documents/<int:document_id>/rag/query/",
        DocumentRagQueryView.as_view(),
        name="document-rag-query",
    ),
    path(
        "documents/<int:document_id>/analyses/",
        DocumentAnalysisRunListView.as_view(),
        name="document-analysis-runs",
    ),
    path(
        "documents/<int:document_id>/controls/run/",
        DocumentControlRunView.as_view(),
        name="document-control-run",
    ),
    path("analysis-controls/", AnalysisControlListCreateView.as_view(), name="analysis-control-list"),
    path(
        "analysis-controls/<int:control_id>/",
        AnalysisControlDetailView.as_view(),
        name="analysis-control-detail",
    ),
    path("jobs/", AsyncJobListView.as_view(), name="job-list"),
    path("jobs/<uuid:job_id>/", AsyncJobDetailView.as_view(), name="job-detail"),
    path("jobs/<uuid:job_id>/cancel/", AsyncJobCancelView.as_view(), name="job-cancel"),
    path("ai/ollama/status/", OllamaStatusView.as_view(), name="ollama-status"),
    path("ai/ollama/pull/", OllamaPullView.as_view(), name="ollama-pull"),
    path("ai/ollama/unload/", OllamaUnloadView.as_view(), name="ollama-unload"),
    path("ai/ollama/chat/", OllamaChatView.as_view(), name="ollama-chat"),
    path("word-to-jira/parse/", WordTableParseView.as_view(), name="word-table-parse"),
    path("word-to-jira/publish/", WordToJiraPublishView.as_view(), name="word-to-jira-publish"),
    path(
        "technical-documents/",
        TechnicalDocumentListCreateView.as_view(),
        name="technical-document-list",
    ),
    path(
        "technical-documents/<int:technical_document_id>/",
        TechnicalDocumentDetailView.as_view(),
        name="technical-document-detail",
    ),
    path(
        "technical-documents/<int:technical_document_id>/notify/",
        TechnicalDocumentNotifyView.as_view(),
        name="technical-document-notify",
    ),
]
